package reporter

import (
	"fmt"
	"html"
	"os"
	"strings"
	"time"

	"github.com/rheatkhs/lurah/scanner"
)

// PrintHTML generates a self-contained HTML report file.
func PrintHTML(findings []scanner.Finding, projectPath string, outputPath string) error {
	var critical, high, medium int
	for _, f := range findings {
		switch f.Severity {
		case scanner.CRITICAL:
			critical++
		case scanner.HIGH:
			high++
		case scanner.MEDIUM:
			medium++
		}
	}

	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lurah Security Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #0f172a; color: #e2e8f0; }
  .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
  .header { text-align: center; padding: 2rem 0; border-bottom: 1px solid #1e293b; margin-bottom: 2rem; }
  .header h1 { font-size: 2rem; color: #f8fafc; margin-bottom: 0.5rem; }
  .header p { color: #94a3b8; }
  .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }
  .card { background: #1e293b; border-radius: 0.75rem; padding: 1.5rem; text-align: center; }
  .card .number { font-size: 2.5rem; font-weight: 700; }
  .card .label { color: #94a3b8; font-size: 0.875rem; margin-top: 0.25rem; }
  .total .number { color: #f8fafc; }
  .critical .number { color: #ef4444; }
  .high .number { color: #f59e0b; }
  .medium .number { color: #06b6d4; }
  table { width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 0.75rem; overflow: hidden; }
  thead th { background: #334155; padding: 0.875rem 1rem; text-align: left; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; }
  tbody td { padding: 0.875rem 1rem; border-top: 1px solid #334155; vertical-align: top; font-size: 0.9rem; }
  .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 700; }
  .badge-critical { background: rgba(239,68,68,0.15); color: #ef4444; }
  .badge-high { background: rgba(245,158,11,0.15); color: #f59e0b; }
  .badge-medium { background: rgba(6,182,212,0.15); color: #06b6d4; }
  .file { color: #60a5fa; font-family: 'Fira Code', monospace; font-size: 0.85rem; }
  .footer { text-align: center; padding: 2rem 0; color: #475569; font-size: 0.8rem; margin-top: 2rem; border-top: 1px solid #1e293b; }
  .success { text-align: center; padding: 3rem; color: #22c55e; font-size: 1.25rem; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Lurah Security Report</h1>
    <p>`)
	sb.WriteString(html.EscapeString(projectPath))
	sb.WriteString(fmt.Sprintf(` &mdash; %s</p>
  </div>

  <div class="summary">
    <div class="card total"><div class="number">%d</div><div class="label">Total Issues</div></div>
    <div class="card critical"><div class="number">%d</div><div class="label">Critical</div></div>
    <div class="card high"><div class="number">%d</div><div class="label">High</div></div>
    <div class="card medium"><div class="number">%d</div><div class="label">Medium</div></div>
  </div>
`, time.Now().Format("2006-01-02 15:04"), len(findings), critical, high, medium))

	if len(findings) == 0 {
		sb.WriteString(`  <div class="success">&#10003; No security issues found.</div>`)
	} else {
		sb.WriteString(`  <table>
    <thead><tr><th>Severity</th><th>File</th><th>Line</th><th>Recommendation</th></tr></thead>
    <tbody>
`)
		for _, f := range findings {
			badgeClass := "badge-medium"
			switch f.Severity {
			case scanner.CRITICAL:
				badgeClass = "badge-critical"
			case scanner.HIGH:
				badgeClass = "badge-high"
			}

			sb.WriteString(fmt.Sprintf(`    <tr>
      <td><span class="badge %s">%s</span></td>
      <td class="file">%s</td>
      <td>%d</td>
      <td>%s</td>
    </tr>
`, badgeClass, f.Severity, html.EscapeString(f.File), f.Line, html.EscapeString(f.Recommendation)))
		}
		sb.WriteString(`    </tbody>
  </table>
`)
	}

	sb.WriteString(fmt.Sprintf(`
  <div class="footer">
    Generated by Lurah v1.0.0 &mdash; Laravel Security Auditor for SPBE Compliance<br>
    %s
  </div>
</div>
</body>
</html>`, time.Now().Format("2006-01-02 15:04:05")))

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}
